version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: health-declaration-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: health-declaration
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  app:
    build: .
    container_name: health-declaration-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://admin:password123@mongodb:27017/health-declaration?authSource=admin
      - PORT=3000
    depends_on:
      - mongodb
    networks: 
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge